name: Build and Deploy
on:
  push:
    tags: ["v*"]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npx vite build
      - uses: oras-project/setup-oras@v1
      - name: Login to OCI Registry
        env:
          OCI_REGISTRY_URL: ${{ secrets.OCI_REGISTRY_URL }}
          OCI_USERNAME: ${{ secrets.OCI_USERNAME }}
          OCI_PASSWORD: ${{ secrets.OCI_PASSWORD }}
        run: |
          REGISTRY_HOST=${OCI_REGISTRY_URL%%/*}
          printf "%s" "$OCI_PASSWORD" | oras login "$REGISTRY_HOST" -u "$OCI_USERNAME" --password-stdin
      - name: Push artifacts
        env:
          OCI_REGISTRY_URL: ${{ secrets.OCI_REGISTRY_URL }}
        run: |
          cd dist
          oras push "$OCI_REGISTRY_URL/app_d4347e7d9867:${{ github.ref_name }}" .
